In [5]:
#Import libs

In [6]:
import numpy as np

In [7]:
#Declare scaler vectors and matrices

In [8]:
#Scaler

In [9]:
s = 5


In [10]:
s


5

In [11]:
v = np.array([1,2,3,4])

In [12]:
v

array([1, 2, 3, 4])

In [13]:
#Matrices

In [14]:
m = np.array([[1,2,3],[4,5,6]])

In [15]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#DataTypes

In [17]:
type(s)

int

In [18]:
type(v)

numpy.ndarray

In [19]:
type(m)

numpy.ndarray

In [20]:
s_array = np.array(5)

In [21]:
type(s_array)

numpy.ndarray

In [22]:
#DataShapes

In [23]:
s_array.shape

()

In [24]:
v.shape

(4,)

In [25]:
m.shape


(2, 3)

In [26]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [27]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [28]:
#Matrices Additon
#Condition: Two matrices must have same dimensions

In [29]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[4,5,6],[1,2,3]])

In [30]:
m1 + m2

array([[5, 7, 9],
       [5, 7, 9]])

In [32]:
#Subtraction
m1-m2

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [33]:
#Scaler Addtion with matrices
1+m1

array([[2, 3, 4],
       [5, 6, 7]])

In [34]:
v + np.array(1)

array([2, 3, 4, 5])

In [35]:
#Transpose
#Important considrations
#1)Values are not changing or tranforming only their position is
#2)Transposing the same vector (object) twice yields the initial vector (object)
#3)A 3x1 matrix transpose is a 1x3 matrix

In [37]:
m1.shape


(2, 3)

In [39]:
m3 = m1.T

In [40]:
m3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
m3.shape

(3, 2)

In [43]:
#Scaler transpose: Any scaler transpose is itself
s_array.T


array(5)

In [45]:
#Vector Transpose: one dimestions arrays don't get transposed
v.shape


(4,)

In [50]:
v.T

array([1, 2, 3, 4])

In [53]:
v_reshaped = v.reshape(1,4)
v_reshaped


array([[1, 2, 3, 4]])

In [54]:
v_reshaped.T

array([[1],
       [2],
       [3],
       [4]])