In [1]:
#Import libs

In [2]:
import numpy as np

In [3]:
#Declare scaler vectors and matrices

In [4]:
#Scaler

In [ ]:
s = 5


In [ ]:
s


5

In [ ]:
v = np.array([1,2,3,4])

In [ ]:
v

array([1, 2, 3, 4])

In [ ]:
#Matrices

In [ ]:
m = np.array([[1,2,3],[4,5,6]])

In [ ]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#DataTypes

In [ ]:
type(s)

int

In [ ]:
type(v)

numpy.ndarray

In [ ]:
type(m)

numpy.ndarray

In [ ]:
s_array = np.array(5)

In [ ]:
type(s_array)

numpy.ndarray

In [ ]:
#DataShapes

In [ ]:
s_array.shape

()

In [ ]:
v.shape

(4,)

In [ ]:
m.shape


(2, 3)

In [ ]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [ ]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])