In [1]:
#Import libs

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Declare scaler vectors and matrices

In [4]:
#Scaler

In [5]:
s = 5


In [6]:
s


5

In [7]:
v = np.array([1,2,3,4])

In [8]:
v

array([1, 2, 3, 4])

In [9]:
#Matrices

In [10]:
m = np.array([[1,2,3],[4,5,6]])

In [11]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
#DataTypes

In [13]:
type(s)

int

In [14]:
type(v)

numpy.ndarray

In [15]:
type(m)

numpy.ndarray

In [16]:
s_array = np.array(5)

In [17]:
type(s_array)

numpy.ndarray

In [18]:
#DataShapes

In [19]:
s_array.shape

()

In [20]:
v.shape

(4,)

In [21]:
m.shape


(2, 3)

In [22]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [23]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [24]:
#Matrices Additon
#Condition: Two matrices must have same dimensions

In [25]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[4,5,6],[1,2,3]])

In [26]:
m1 + m2

array([[5, 7, 9],
       [5, 7, 9]])

In [27]:
#Subtraction
m1-m2

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [28]:
#Scaler Addtion with matrices
1+m1

array([[2, 3, 4],
       [5, 6, 7]])

In [29]:
v + np.array(1)

array([2, 3, 4, 5])

In [30]:
#Transpose
#Important considrations
#1)Values are not changing or tranforming only their position is
#2)Transposing the same vector (object) twice yields the initial vector (object)
#3)A 3x1 matrix transpose is a 1x3 matrix

In [31]:
m1.shape


(2, 3)

In [32]:
m3 = m1.T

In [33]:
m3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
m3.shape

(3, 2)

In [35]:
#Scaler transpose: Any scaler transpose is itself
s_array.T


array(5)

In [36]:
#Vector Transpose: one dimestions arrays don't get transposed
v.shape


(4,)

In [37]:
v.T

array([1, 2, 3, 4])

In [38]:
v_reshaped = v.reshape(1,4)
v_reshaped

array([[1, 2, 3, 4]])

In [39]:
v_reshaped.T

array([[1],
       [2],
       [3],
       [4]])

In [40]:
#Vector Multiplication: Sum of the product of corresponding element
#Conditon: They must have same length
#Dot or inner product
#Tensor or outer product
#Multiplication of two vector is a scaler

In [41]:
#Dot product

In [42]:
x1 = np.array([0,2,3,4])
x2 = np.array([4,2,4,1])


In [43]:
np.dot(x1,x2)

20

In [44]:
#Scaler * Scaler


In [45]:
np.dot(12,21)

252

In [46]:
#Vector * Scaler


In [47]:
x1

array([0, 2, 3, 4])

In [48]:
x1*5

array([ 0, 10, 15, 20])

In [49]:
#Scaler * Matrices

In [50]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
m1*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [52]:
#Matrices * Matrices
#Condotion: Can only multiply m x n with an n x k 
#output m x n * n x k = m x k

In [53]:
m1=np.array([[5 , 12 ,6],[-3,0,14]])
m2=np.array([[2,-1],[8,0],[3,0]])

In [54]:
np.dot(m1,m2)

array([[124,  -5],
       [ 36,   3]])

In [55]:
m1=np.array([[1],[2],[3]]) #1 by 3
m2=np.array([[1],[2],[3]]) #3 by 1

In [56]:
np.dot(m1,m2.T)


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [57]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [58]:
array_b = np.array([[1,2,3],[2,1,4]])
array_b

array([[1, 2, 3],
       [2, 1, 4]])

In [59]:
np.mean(array_b)

2.1666666666666665

In [60]:
#Pandas Basics

In [61]:
products=['A','B']
type(products)

list

In [62]:
product_categories=pd.Series(products)
product_categories

0    A
1    B
dtype: object

In [63]:
#Always store same type of data in series

In [64]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [65]:
series1=pd.Series(array1)
series1 

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [66]:
series1.dtypes

dtype('int32')

In [67]:
series1.dtype

dtype('int32')

In [68]:
series1.size

5

In [69]:
product_categories.dtype

dtype('O')

In [70]:
product_categories.size

2

In [71]:
product_categories.name = "Product Categories"

In [72]:
product_categories.name


'Product Categories'

In [73]:
#Understanding indexes in pandas
dict1 = {'Product A': 121,'Product B': 41121,'Product C': 12211}
dict1

{'Product A': 121, 'Product B': 41121, 'Product C': 12211}

In [74]:
type(dict1)

dict

In [75]:
DictIntoSeries= pd.Series(dict1)
DictIntoSeries 

Product A      121
Product B    41121
Product C    12211
dtype: int64

In [76]:
type(DictIntoSeries)

pandas.core.series.Series

In [77]:
DictIntoSeries.index

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [78]:
#Label based vs Position based indexing
series1.index

RangeIndex(start=0, stop=5, step=1)

In [79]:
type(series1.index)

pandas.core.indexes.range.RangeIndex

In [80]:
list(series1.index)

[0, 1, 2, 3, 4]

In [81]:
series1 #Implicit Indexing or zero based/position based indexing

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [82]:
DictIntoSeries #Explicit Indexing or label based Indexing

Product A      121
Product B    41121
Product C    12211
dtype: int64

In [83]:
start_date_deposite = pd.Series({'7/4/2014':2000 , '7/5/2014':1000 , '7/6/2014':5000})

In [84]:
start_date_deposite.sum()


8000

In [85]:
start_date_deposite.max()

5000

In [86]:
start_date_deposite.min()

1000

In [87]:
start_date_deposite.idxmax()

'7/6/2014'

In [88]:
start_date_deposite.idxmin()

'7/5/2014'

In [89]:
start_date_deposite.mean()

2666.6666666666665

In [90]:
start_date_deposite.median()

2000.0

In [91]:
start_date_deposite.std()

2081.6659994661327

In [92]:
#Non mathematical methods or methods that are specific to pandas
start_date_deposite.head()

7/4/2014    2000
7/5/2014    1000
7/6/2014    5000
dtype: int64

In [93]:
start_date_deposite.tail()

7/4/2014    2000
7/5/2014    1000
7/6/2014    5000
dtype: int64

In [94]:
#Parameters and arguments
start_date_deposite.head(2)

7/4/2014    2000
7/5/2014    1000
dtype: int64

In [98]:
#Construct DataFrames from a dictionary of lists
data = {'ProductName': ['Product A','Product B','Product C'], 'ProductPrice':[1212,3123,4124]}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
0   Product A          1212
1   Product B          3123
2   Product C          4124

In [99]:
#Construct DataFrames from a dictionary of lists + specify index
data = {'ProductName': ['Product A','Product B','Product C'], 'ProductPrice':[1212,3123,4124]}
df = pd.DataFrame(data, index=['A','B','C'])
df

ProductName  ProductPrice
A   Product A          1212
B   Product B          3123
C   Product C          4124

In [100]:
data = {'ProductName': ['Product A','Product B','Product C'], 'ProductPrice':[1212,3123,4124]}
product_ID=['A','B','C']
df = pd.DataFrame(data, product_ID)
df

ProductName  ProductPrice
A   Product A          1212
B   Product B          3123
C   Product C          4124

In [121]:
#Construct DataFrames from a list of dictionaries
data = [{'ProductName':'Product A', 'ProductPrice':2000},
        {'ProductName':'Product B', 'ProductPrice':4000},
        {'ProductName':'Product B', 'ProductPrice':1000},
        ]
df = pd.DataFrame(data, product_ID)
df

ProductName  ProductPrice
A   Product A          2000
B   Product B          4000
C   Product B          1000

In [129]:
ser_products=pd.Series(['Product A', 'Product B', 'Product C'], index=['A','B','C'])
ser_price=pd.Series([1212,3123,4124], index=['B','A','C'])
data = {'ProductName':ser_products, 'ProductPrice':ser_price}
df = pd.DataFrame(data)
df

ProductName  ProductPrice
A   Product A          3123
B   Product B          1212
C   Product C          4124

In [131]:
df= pd.DataFrame(data=[['Product A', 1212],['Product B', 3123],['Product C', 4124]], columns=['ProductName','ProductPrice'],index=['A','B','C'])
data

ProductName  ProductPrice
A   Product A          1212
B   Product B          3123
C   Product C          4124