In [158]:
#Import libs

In [159]:
import numpy as np
import pandas as pd

In [160]:
#Declare scaler vectors and matrices

In [161]:
#Scaler

In [162]:
s = 5


In [163]:
s


5

In [164]:
v = np.array([1,2,3,4])

In [165]:
v

array([1, 2, 3, 4])

In [166]:
#Matrices

In [167]:
m = np.array([[1,2,3],[4,5,6]])

In [168]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
#DataTypes

In [170]:
type(s)

int

In [171]:
type(v)

numpy.ndarray

In [172]:
type(m)

numpy.ndarray

In [173]:
s_array = np.array(5)

In [174]:
type(s_array)

numpy.ndarray

In [175]:
#DataShapes

In [176]:
s_array.shape

()

In [177]:
v.shape

(4,)

In [178]:
m.shape


(2, 3)

In [179]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [180]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [181]:
#Matrices Additon
#Condition: Two matrices must have same dimensions

In [182]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[4,5,6],[1,2,3]])

In [183]:
m1 + m2

array([[5, 7, 9],
       [5, 7, 9]])

In [184]:
#Subtraction
m1-m2

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [185]:
#Scaler Addtion with matrices
1+m1

array([[2, 3, 4],
       [5, 6, 7]])

In [186]:
v + np.array(1)

array([2, 3, 4, 5])

In [187]:
#Transpose
#Important considrations
#1)Values are not changing or tranforming only their position is
#2)Transposing the same vector (object) twice yields the initial vector (object)
#3)A 3x1 matrix transpose is a 1x3 matrix

In [188]:
m1.shape


(2, 3)

In [189]:
m3 = m1.T

In [190]:
m3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [191]:
m3.shape

(3, 2)

In [192]:
#Scaler transpose: Any scaler transpose is itself
s_array.T


array(5)

In [193]:
#Vector Transpose: one dimestions arrays don't get transposed
v.shape


(4,)

In [194]:
v.T

array([1, 2, 3, 4])

In [195]:
v_reshaped = v.reshape(1,4)
v_reshaped

array([[1, 2, 3, 4]])

In [196]:
v_reshaped.T

array([[1],
       [2],
       [3],
       [4]])

In [197]:
#Vector Multiplication: Sum of the product of corresponding element
#Conditon: They must have same length
#Dot or inner product
#Tensor or outer product
#Multiplication of two vector is a scaler

In [198]:
#Dot product

In [199]:
x1 = np.array([0,2,3,4])
x2 = np.array([4,2,4,1])


In [200]:
np.dot(x1,x2)

20

In [201]:
#Scaler * Scaler


In [202]:
np.dot(12,21)

252

In [203]:
#Vector * Scaler


In [204]:
x1

array([0, 2, 3, 4])

In [205]:
x1*5

array([ 0, 10, 15, 20])

In [206]:
#Scaler * Matrices

In [207]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
m1*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [209]:
#Matrices * Matrices
#Condotion: Can only multiply m x n with an n x k 
#output m x n * n x k = m x k

In [210]:
m1=np.array([[5 , 12 ,6],[-3,0,14]])
m2=np.array([[2,-1],[8,0],[3,0]])

In [211]:
np.dot(m1,m2)

array([[124,  -5],
       [ 36,   3]])

In [212]:
m1=np.array([[1],[2],[3]]) #1 by 3
m2=np.array([[1],[2],[3]]) #3 by 1

In [213]:
np.dot(m1,m2.T)


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [214]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [215]:
array_b = np.array([[1,2,3],[2,1,4]])
array_b

array([[1, 2, 3],
       [2, 1, 4]])

In [216]:
np.mean(array_b)

2.1666666666666665

In [217]:
#Pandas Basics

In [218]:
products=['A','B']
type(products)

list

In [219]:
product_categories=pd.Series(products)
product_categories

0    A
1    B
dtype: object

In [220]:
#Always store same type of data in series

In [221]:
array1 = np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [222]:
series1=pd.Series(array1)
series1 

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [223]:
series1.dtypes

dtype('int32')

In [224]:
series1.dtype

dtype('int32')

In [225]:
series1.size

5

In [226]:
product_categories.dtype

dtype('O')

In [227]:
product_categories.size

2

In [228]:
product_categories.name = "Product Categories"

In [229]:
product_categories.name


'Product Categories'

In [230]:
#Understanding indexes in pandas
dict1 = {'Product A': 121,'Product B': 41121,'Product C': 12211}
dict1

{'Product A': 121, 'Product B': 41121, 'Product C': 12211}

In [231]:
type(dict1)

dict

In [232]:
DictIntoSeries= pd.Series(dict1)
DictIntoSeries 

Product A      121
Product B    41121
Product C    12211
dtype: int64

In [233]:
type(DictIntoSeries)

pandas.core.series.Series

In [234]:
DictIntoSeries.index

Index(['Product A', 'Product B', 'Product C'], dtype='object')

In [242]:
#Label based vs Position based indexing
series1.index

RangeIndex(start=0, stop=5, step=1)

In [243]:
type(series1.index)

pandas.core.indexes.range.RangeIndex

In [249]:
list(series1.index)

[0, 1, 2, 3, 4]

In [253]:
series1 #Implicit Indexing or zero based/position based indexing

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [254]:
DictIntoSeries #Explicit Indexing or label based Indexing

Product A      121
Product B    41121
Product C    12211
dtype: int64

In [255]:
start_date_deposite = pd.Series({'7/4/2014':2000 , '7/5/2014':1000 , '7/6/2014':5000})

In [262]:
start_date_deposite.sum()


8000

In [263]:
start_date_deposite.max()

5000

In [264]:
start_date_deposite.min()

1000

In [265]:
start_date_deposite.idxmax()

'7/6/2014'

In [266]:
start_date_deposite.idxmin()

'7/5/2014'

In [267]:
start_date_deposite.mean()

2666.6666666666665

In [268]:
start_date_deposite.median()

2000.0

In [269]:
start_date_deposite.std()

2081.6659994661327