In [179]:
#Import libs

In [180]:
import numpy as np

In [181]:
#Declare scaler vectors and matrices

In [182]:
#Scaler

In [183]:
s = 5


In [184]:
s


5

In [185]:
v = np.array([1,2,3,4])

In [186]:
v

array([1, 2, 3, 4])

In [187]:
#Matrices

In [188]:
m = np.array([[1,2,3],[4,5,6]])

In [189]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
#DataTypes

In [191]:
type(s)

int

In [192]:
type(v)

numpy.ndarray

In [193]:
type(m)

numpy.ndarray

In [194]:
s_array = np.array(5)

In [195]:
type(s_array)

numpy.ndarray

In [196]:
#DataShapes

In [197]:
s_array.shape

()

In [198]:
v.shape

(4,)

In [199]:
m.shape


(2, 3)

In [200]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [201]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [202]:
#Matrices Additon
#Condition: Two matrices must have same dimensions

In [203]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[4,5,6],[1,2,3]])

In [204]:
m1 + m2

array([[5, 7, 9],
       [5, 7, 9]])

In [205]:
#Subtraction
m1-m2

array([[-3, -3, -3],
       [ 3,  3,  3]])

In [206]:
#Scaler Addtion with matrices
1+m1

array([[2, 3, 4],
       [5, 6, 7]])

In [207]:
v + np.array(1)

array([2, 3, 4, 5])

In [208]:
#Transpose
#Important considrations
#1)Values are not changing or tranforming only their position is
#2)Transposing the same vector (object) twice yields the initial vector (object)
#3)A 3x1 matrix transpose is a 1x3 matrix

In [209]:
m1.shape


(2, 3)

In [210]:
m3 = m1.T

In [211]:
m3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [212]:
m3.shape

(3, 2)

In [213]:
#Scaler transpose: Any scaler transpose is itself
s_array.T


array(5)

In [214]:
#Vector Transpose: one dimestions arrays don't get transposed
v.shape


(4,)

In [215]:
v.T

array([1, 2, 3, 4])

In [216]:
v_reshaped = v.reshape(1,4)
v_reshaped


array([[1, 2, 3, 4]])

In [217]:
v_reshaped.T

array([[1],
       [2],
       [3],
       [4]])

In [218]:
#Vector Multiplication: Sum of the product of corresponding element
#Conditon: They must have same length
#Dot or inner product
#Tensor or outer product
#Multiplication of two vector is a scaler

In [219]:
#Dot product

In [220]:
x1 = np.array([0,2,3,4])
x2 = np.array([4,2,4,1])


In [221]:
np.dot(x1,x2)

20

In [222]:
#Scaler * Scaler


In [223]:
np.dot(12,21)

252

In [224]:
#Vector * Scaler


In [225]:
x1

array([0, 2, 3, 4])

In [226]:
x1*5

array([ 0, 10, 15, 20])

In [227]:
#Scaler * Matrices

In [228]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [229]:
m1*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [230]:
#Matrices * Matrices
#Condotion: Can only multiply m x n with an n x k 
#output m x n * n x k = m x k

In [231]:
m1=np.array([[5 , 12 ,6],[-3,0,14]])
m2=np.array([[2,-1],[8,0],[3,0]])

In [232]:
np.dot(m1,m2)

array([[124,  -5],
       [ 36,   3]])

In [233]:
m1=np.array([[1],[2],[3]]) #1 by 3
m2=np.array([[1],[2],[3]]) #3 by 1

In [234]:
np.dot(m1,m2.T)


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [235]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [236]:
array_b = np.array([[1,2,3],[2,1,4]])
array_b

array([[1, 2, 3],
       [2, 1, 4]])

In [237]:
np.mean(array_b)

2.1666666666666665